### ISSUE TITLE
Does this work with updated Facebook UX?

### ISSUE THREAD

**Issue by chieber13** [lgwb89/nudge#74] opened 2020-04-01 18:54 UTC

**Comment by lgwb89** [comment] 2020-04-10 20:21
No it doesn't, but it's on my to do list.

**Comment by lgwb89** [comment] 2020-04-22 11:24
More info on this: the Unfollower, specifically, doesn't work on new Facebook UX. It seems this is more than just a trivial fix, since Facebook updated the way unfollowing works in terms of web requests, so I need to spend some time digging into how to reproduce what they do. I will keep updates posted here.

**Comment by lgwb89** [comment] 2020-04-29 09:45
Update: looks like the same web requests for the old version of the site can still be used, which makes sense. I am going to try re-enable the Unfollower in the next week or so.

**Comment by chieber13** [comment] 2020-04-29 15:14
Thank you for the update

Please excuse brevity or typos - sent from my moblie.
www.colleenhieber.com

**Comment by lgwb89** [comment] 2020-04-30 11:12
Update: I got the Unfollower working again, now on old Facebook and new Facebook. Deploying the update shortly and should get to your devices in around 4/5 days (because of weekend). I will close this now but please reopen if you continue to experience issues on new Facebook after then.

Screenshot:

![Uploading image.png…]()

**Closed by lgwb89** 2020-04-30 11:12 UTC

**Comment by chieber13** [comment] 2020-04-30 15:26
Great - thanks!

*Colleen Hieber*
Ready to get healthy? <https://www.colleenhieber.com/>
