### ISSUE TITLE
"this extension may be corrupted" after visiting settings page

### ISSUE THREAD

**Issue by ncrowell** [lgwb89/nudge#60] opened 2020-02-15 00:14 UTC
Hello, I'm trying to install the extension. I can make it through most of the sign-up pages, but skipping the unfollower step, OR exiting from the sign-up early and clicking `Settings` or `Options` from the URL icon menu, causes the extension to immediately close.

Then, there is a message saying `this extension may be corrupted` in chrome://extensions. You can click `Repair to fix the extension`, but the same issue occurs.

**Comment by aadilayub** [comment] 2020-02-16 16:27
I'm experiencing this issue as well. Usually, it stops working after the Greyify Facebook section.

**Comment by lgwb89** [comment] 2020-02-18 15:22
Apologies for this and thank you for reporting. I'm struggling to reproduce. Is there any chance you could go to chrome://extensions, find Nudge's background page in the Nudge section, open it and send me a screenshot of any error there?

**Comment by lgwb89** [comment] 2020-02-18 15:31
Also - could be related to a bug that I fixed in the latest release (currently under review on Chrome Web Store and should land with you in the next couple of days).

**Comment by aadilayub** [comment] 2020-02-19 06:32
So I actually got the extension to work by closing the initial set-up/configuration flow before reaching the "Greyify Facebook " section.

Going to `chrome://extensions`, things seem normal:

![image](https://user-images.githubusercontent.com/31581044/74807527-8424bd00-530a-11ea-8f56-b0e93c2be475.png)

![image](https://user-images.githubusercontent.com/31581044/74807556-9272d900-530a-11ea-8802-732197d96468.png)

I tried to get the extension to break by reinstalling it and going through the set-up section, but this time it didn't crash. Maybe I got the new release? The version number is 1.0.49.

**Comment by crColeman** [comment] 2020-02-26 22:45
I just ran into this same issue after discovering Nudge and installing it for the first time. Upon going through the initial setup of enabling features and reaching the last page, once I clicked the button to continue and finish the page immediately closes and nothing appeared to change on my browser. On the chrome://extensions page it shows that the "plugin may be corrupted" and does not allow for the plugin to be enabled by greying out the option.

However, I found that if I clicked the link at the bottom of Nudge's settings page in chrome://extensions and clicked the "View in Chrome Web Store" link, it displayed a drop down notification that informed me the plugin was disabled and had a hyperlinked text to enable which then enabled the plugin and the preferences I originally selected in the setup still existed. 
![nudgeDisabled](https://user-images.githubusercontent.com/45726175/75394824-3e3d9b00-58ae-11ea-8ee7-adf33201630c.png)

I also found that clicking the settings option in the nudge dropdown after getting it work again caused the plugin to be shown as corrupted again but I can go back through the process I described before to re-enable. The plugin is not affected by selecting any other options available in the dropdown menu besides the settings option. 

Chrome: Version 80.0.3987.106 (Official Build) (64-bit)
OS: Fedora 31

**Comment by lgwb89** [comment] 2020-03-03 13:28
@aadilayub Thank you for the detailed extra information. Have you seen this problem reoccur? I'm hoping it was fixed in a recent release.

@crColeman Appreciate the report here, and many apologies for this. Can you tell me which version # of Nudge you are on? And if the problem is still reoccuring? I will try and reproduce.

**Comment by lgwb89** [comment] 2020-03-03 13:28
Accidental close, sorry! I'm not getting away with it that easily... :)

**Comment by aadilayub** [comment] 2020-03-04 03:21
> @aadilayub Thank you for the detailed extra information. Have you seen this problem reoccur? I'm hoping it was fixed in a recent release.
> 
> @crColeman Appreciate the report here, and many apologies for this. Can you tell me which version # of Nudge you are on? And if the problem is still reoccuring? I will try and reproduce.

I did! Happened while installing nudge on Brave a couple of days ago.

**Comment by ncrowell** [comment] 2020-03-05 05:51
It's difficult to find an error from the background page, because the background page console closes at the same time as the extension crashing. If there is any way to grab a file that might contain any relevant logs even after the extension becomes "corrupted", I can do that.

**Comment by lgwb89** [comment] 2020-04-29 09:44
I think this should no longer be an issue since the latest release which handles settings better. I will close for now but please reopen if I am wrong.

**Closed by lgwb89** 2020-04-29 09:44 UTC
